### ISSUE TITLE
GUI Front-end

### ISSUE THREAD

**Issue by jpt13653903** [jpt13653903/Gerber2PDF#10]
I've had some requests for a GUI front-end to the command-line tool.  Unfortunately, I don't have time to implement, as my day-job is keeping me rather busy at the moment...

If you're interested in taking up the task, feel free to open up a discussion on this feature request to discuss potential features, look-and-feel, etc.

Please keep it platform independent.  Python is good choice.  I was also thinking that a web-based solution might be a good option, albeit a bit limited in functionality.

**Comment by happycoder97** [comment]
Hi, I'm interested in implementing the GUI :)
I know a bit of GTK and dear ImGui (https://github.com/ocornut/imgui).
Languages C, C++, Python and Rust

**Comment by jpt13653903** [comment]
Excellent :-)  I'm looking forward to see what you come up with.

I would prefer it if the GUI is free-standing (use the [GUI folder](https://github.com/jpt13653903/Gerber2PDF/tree/feature/GUI/GUI) for the source).  I'm looking for something akin to an IDE: in other words, something that gives the user the ability to easily input all the options, but still calls the command-line version in the background.

Shall we start with a couple of rough concept sketches?  Pen-and-paper should be fine: you can dump them in the [Docs/GUI/Concept folder](https://github.com/jpt13653903/Gerber2PDF/tree/feature/GUI/Docs/GUI/Concept) of the [feature/GUI branch](https://github.com/jpt13653903/Gerber2PDF/tree/feature/GUI) and do a pull-request.

I'll leave the choice of tools / framework / infrastructure up to you.

**Comment by happycoder97** [comment]
First draft of GUI:

![out](https://user-images.githubusercontent.com/40014472/48433473-359a8180-e79d-11e8-93a3-b93466d29abf.png)

**Comment by happycoder97** [comment]
The colored rectangle on the left, when clicked, will open a color chooser pop up.

**Comment by jpt13653903** [comment]
I really like where you're heading with it.  Nice and simple :-)

I would like to add a button (maybe next to the "Convert" button) that
exports the batch script.

Otherwise - run with it.

**Comment by jpt13653903** [comment]
The `-combine` flag puts it into "combine layers onto a single page" mode.  All files specified thereafter are combined.

The "-nocombine" mode reverts to the default "one layer - one page" mode.

If you don't specify flags it uses whatever was specified last -- it's all modal.  In the case of the example in the Docs readme, it reverts to black on white.

**Comment by happycoder97** [comment]
So specifying `-combine file1.gbr file2.gbr -combine file3.gbr file4.gbr` puts file1 and file2 combined in one page, file3 and file4 in next page?

**Comment by jpt13653903** [comment]
Hope you don't mind -- I moved the concept design to [here](https://github.com/jpt13653903/Gerber2PDF/tree/feature/GUI/Docs/GUI/Concept)

**Comment by jpt13653903** [comment]
> 
> 
> So specifying `-combine file1.gbr file2.gbr -combine file3.gbr file4.gbr` puts file1 and file2 combined in one page, file3 and file4 in next page?

Exactly

**Comment by jpt13653903** [comment]
The whole project was originally meant as a simple unit-test for my Gerber and PDF libraries -- never thought it would be so popular...  The code itself is therefore much more messy that it should be.

This said -- you'll find the command-line parser [here](https://github.com/jpt13653903/Gerber2PDF/blob/241abbf36507ca3cbe021a1f3ad6b5aa987ce01a/Source/main.cpp#L625).

A minus sign as the first character triggers a mode change.  Otherwise the parameter is a Gerber file to be converted.

Modes are simply global variables, defined [here](https://github.com/jpt13653903/Gerber2PDF/blob/241abbf36507ca3cbe021a1f3ad6b5aa987ce01a/Source/main.cpp#L25) and [here](https://github.com/jpt13653903/Gerber2PDF/blob/241abbf36507ca3cbe021a1f3ad6b5aa987ce01a/Source/main.h#L29).

**Comment by jpt13653903** [comment]
You might be interested in [an example](https://github.com/jpt13653903/Gerber2PDF/tree/feature/GUI/Examples/USB%20PIC).

**Comment by happycoder97** [comment]
Thanks for the details :)

**Comment by happycoder97** [comment]
I should do further commits in master branch only, right?

**Comment by jpt13653903** [comment]
You were actually not supposed to merge it...  I opened up the pull request
so I can get email updates on your commits.

No matter ;-)

Carry on with commits to feature/GUI - I'll re-open the pull-request.

**Comment by jpt13653903** [comment]
I'm going to do an experiment...  I see the pull request has a "revert" option that I've always wondered what it does...

**Comment by jpt13653903** [comment]
> 
> 
> I'm going to do an experiment... I see the pull request has a "revert" option that I've always wondered what it does...

Never mind -- it doesn't do what I was hoping.  I'll make a small update to feature/GUI and create a new pull-request...

**Comment by jpt13653903** [comment]
My apologies for confusing you...

The "revert-11-feature/GUI" branch was an experiment that failed.  I'm going to delete that branch as soon I've merged your new stuff into "feature/GUI".

Every time you commit to "feature/GUI" I should get an email update (because of the pull-request).  I cannot "subscribe" to the branch any other way -- GitHub does not have that feature.

So please continue developing on "feature/GUI".

Thanks ;-)

**Comment by jpt13653903** [comment]
I'm closing this issue -- the GUI is well on it's way on pull-request #12
