### ISSUE TITLE
Ubuntu 20 LTS: Make fails

### ISSUE THREAD

**Issue by g40** [jpt13653903/Gerber2PDF#21]
Hello. Apologies if this is missing some of the suggested bug report elements but ... any thoughts welcomed. 

Attempting to build from fresh clone of master here on Github:

```
~/src/Gerber2PDF$ make
make -C Engine all
make[1]: Entering directory '/home/moi/src/Gerber2PDF/Engine'
make[1]: *** No rule to make target 'obj_lin/Tools/Deflate/JDeflate.o', needed by 'obj_lin/libEngine.a'. Stop.
make[1]: Leaving directory '/home/moi/src/Gerber2PDF/Engine'
make: *** [Makefile:14: Engine] Error 2
```

```
$ uname -a
Linux ubuntu 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
Licence GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by jlhavens** [comment]
Could not download from SourceForge (repeated attempts failed to download in three different environments) so also tried to compile on Linux machine and got the same make error.

**Comment by jpt13653903** [comment]
That error is very typical if the submodules haven't been cloned, so: have you run "git submodule update --init --recursive" after the clone?

**Comment by jpt13653903** [comment]
I'm also having trouble downloading from SourceForge at the moment...  I'll investigate and get back to you...

**Comment by jpt13653903** [comment]
I re-uploaded the files to SourceForge and it seems to be working now...

Please could you confirm so I can close the issue?

**Comment by jpt13653903** [comment]
By the way -- I use two different Linux environments to compile, depending on where I'm working...

1. Ubuntu 14.04 LTS running in a VirtualBox VM
2. Ubuntu 18.04 LTS running in Windows Subsystem for Linux

The Windows version is compiled natively in Windows using MinGW (the current version I'm using is tdm64-1 9.2.0)

I have also tested it on a natively installed Scientific Linux.  I'm fairly certain your issue is the submodules...

**Comment by jlhavens** [comment]
Yes, was able to download.  Thanks for all the help.

Jeff

________________________________

**Comment by jpt13653903** [comment]
Pleasure :-)
