### ISSUE TITLE
ZLib Error

### ISSUE THREAD

**Issue by jpt13653903** [jpt13653903/Gerber2PDF#23]
When using GhostScript to reduce the output PDF size, it complains: `warning: ignoring zlib error: incorrect data check`

The command-line used is `gswin64c -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -dCompatibilityLevel=1.3 -dPDFSETTINGS=/screen -dEmbedAllFonts=true -dSubsetFonts=true -dColorImageDownsampleType=/Bicubic -dColorImageResolution=144 -dGrayImageDownsampleType=/Bicubic -dGrayImageResolution=144 -dMonoImageDownsampleType=/Bicubic -dMonoImageResolution=144 -sOutputFile=P2-510xxxx_xx_gs.pdf P2-510xxxx_xx.pdf`

**Comment by JonThe640** [comment]
Is it a long and hard work for you?

**Comment by jpt13653903** [comment]
Probably not, but I don't foresee finding sufficient time any time soon.

I will keep this thread posted with comments when I do any updates though.

**Comment by JonThe640** [comment]
I can't wait to try the new update to try reducing file size with ghostscript.    Thanks again and Marry Christmas!!!

**Comment by JonThe640** [comment]
Happy New year 2023 John-Philip and thanks for your support !!!

Jonathan


Merci / Thanks

Jonathan Thérien
Sr PCB designer
Kontron
4555, rue Ambroise-Lafortune | Boisbriand (Québec) J7H 0A4 | Canada
T/P: +1 450 437 4661 x2216
***@***.******@***.***>

Website<http://www.kontron.com/> | Blog<http://blog.kontron.com/> | Twitter<https://twitter.com/Kontron> | LinkedIn<https://www.linkedin.com/company/kontron> | YouTube<https://www.youtube.com/channel/UCXkp_1gJbG0Um1vzdowlqww> | Facebook<https://www.facebook.com/kontron>
Kontron Canada Inc.
En ouvrant ce courriel, vous acceptez la politique de Kontron relative aux communications électroniques<http://www.kontron.com/additional/informations-legales-et-droits-d-auteur>.
By opening this email you are agreeing to Kontron's Electronic Communications Policy<http://www.kontron.com/additional/legal-and-copyright-information>.



De : John-Philip Taylor ***@***.***>
Envoyé : 7 décembre 2022 15:58
À : jpt13653903/Gerber2PDF ***@***.***>
Cc : Jonathan Therien ***@***.***>; Manual ***@***.***>
Objet : Re: [jpt13653903/Gerber2PDF] ZLib Error (Issue #23)

***@***.******@***.***> semble vous avoir déjà envoyé du courrier, mais peut-être s'agit-il d'une autre personne. Découvrez pourquoi cela pourrait constituer un risque<https://aka.ms/LearnAboutSenderIdentification>

Probably not, but I don't foresee finding sufficient time any time soon.

I will keep this thread posted with comments when I do any updates though.

-

**Comment by JonThe640** [comment]
Hello John, any update about your project?

**Comment by jpt13653903** [comment]
I really don't foresee finding sufficient time any time soon.  My day job is keeping me busy -- expect months, rather than weeks.

**Comment by JonThe640** [comment]
Hi John, how are you? Did you find time to work on this issue this spring?   Thanks and have a nice day!

**Comment by jpt13653903** [comment]
Hello,  I'm doing well, thank you :-)

I don't really want to keep you on a line, so let's fix a date...  My best estimate at the moment is that I'll find some time over the summer holidays (i.e. late December in South Africa).  I strongly doubt anything will happen before then -- too much stuff happening in my day-job.

If you happen to have a friend who knows his way around a G++ compiler, he can replace [JDeflate](https://github.com/jpt13653903/Gerber2PDF/tree/master/Engine/Tools/Deflate) with a more sensible implementation with similar interface (maybe using the ZLib library instead of my own silly attempt I did back in the day as a fun exercise) and send me a pull-request...

**Comment by JonThe640** [comment]
thanks for the update.

**Comment by JonThe640** [comment]
Hi John, how are you? Did you find time to work on this issue this winter? Thanks and have a nice day!

**Comment by jpt13653903** [comment]
Still doing well - thank you.

And no - the ETA is still late December

**Comment by jpt13653903** [comment]
I've started looking into this...  You can follow what I'm doing in the `feature/zlib` branch.  My plan is to simply refactor my Deflate class to use the zlib library instead, and then we can go from there...  I have not tried to reproduce your error yet.

**Comment by jpt13653903** [comment]
@JonThe640 
I have not tried to reproduce your issue -- I simply updated the code-base to use the industry-standard ZLib library instead of my own implementation.  Please could you confirm if your issue is now resolved?

**Comment by JonThe640** [comment]
Hi John, happy new year.    I will try it and i will confirm if it works for me.   thanks!!

**Comment by JonThe640** [comment]
Hi John, i cant run the .exe file because my compagny use anti virus bitdefender and each time i want to run the file, bitdefender delete the file.   We added the .exe in the bitdefender exclusion but its not work, the file was deleted.  So i will come back when we repaired this issue.

**Comment by JonThe640** [comment]
hi J-P,  i tried at my home and when i execute the file Gerber2pdf.exe.   It give me an error  

![Capture](https://github.com/jpt13653903/Gerber2PDF/assets/120030151/3c1dd212-23a1-4d77-937e-cd8d583027f6)

**Comment by jpt13653903** [comment]
Thanks for testing...
I thought I statically linked it so that you don't need the DLL -- obviously not...  I'll try again

**Comment by jpt13653903** [comment]
Update available [here](https://github.com/jpt13653903/Gerber2PDF/releases/tag/Version_1.9)

Let's hope this one works better...

**Comment by JonThe640** [comment]
thanks, no error now!

**Comment by jpt13653903** [comment]
Awesome news :-)

let me know when you've thoroughly tested it -- then I'll close this issue.

**Comment by JonThe640** [comment]
i cant test it because bitdefender  deleted the .exe all the time.   We put it in the exlusions but it stopped it.   sorry!

**Comment by JonThe640** [comment]
Hi, i sent you an email about a bug when we have copper plane.  Thanks!!    
![image](https://github.com/jpt13653903/Gerber2PDF/assets/120030151/e19e2eea-34ed-47c0-bf43-2a2e0a6ecf02)

**Comment by jpt13653903** [comment]
Got it -- I'll have a look over the weekend :-)

**Comment by jpt13653903** [comment]
I'm going to move this to a new issue -- it's not about ZLib anymore...
