### ISSUE TITLE
some problem FileWrapper.h

### ISSUE THREAD

**Issue by wj5449** [jpt13653903/Gerber2PDF#24]
Please consult the [SourceForge Discussion](https://sourceforge.net/p/gerber2pdf/discussion) page before asking a question.
hi,
when i use the code ,
 i cannot find filewrapper.h ?
how do I get this file .
 Thanks

**Comment by jpt13653903** [comment]
Hi,

It's part of the [Toolbox submodule](https://github.com/jpt13653903/Toolbox/blob/3b59fbdc7b64cda9befaf5b9fd829a49a9b1f444/Cpp/FileWrapper.h).  After you've cloned the Gerber2PDF repo, run `git submodule update --init --recursive`.

**Comment by wj5449** [comment]
thanks a lot
