### ISSUE TITLE
Searchable pdf

### ISSUE THREAD

**Issue by Dzarda7** [jpt13653903/Gerber2PDF#25]
Hello,

thank you for this project. I would like to ask you if it is possible to make pdf generated from gerber searchable. It would be great, but I do not even know if it is possible. I tried some online pdf ocr webpages, but it works just partially and pdf is not vector after that.

Thanks.

**Comment by jpt13653903** [comment]
Although that would be really awesome, the Gerber file format does not do text.  It does the glyphs as raw vector images.  I don't even have them as letter names, in which case I could have done text extraction.

This said - many CAD tools (like KiCAD and Altium) can export to PDF directly, in which case it is searchable.

**Comment by Dzarda7** [comment]
But it does not support export into one pdf. Would it be at least possible to take pdf as input? Thanks.

**Comment by jpt13653903** [comment]
You'll probably be better off using a PDF editor in that case.  Something along the lines of [Foxit](https://www.foxit.com/pdf-editor/).  I have not used it myself, but you might even be able to script it as part of the "build" workflow.

This said, I don't think it can combine layers like Gerber2PDF can.  I don't believe I'll be able to take a PDF input without significant development effort -- the PDF standard is too generic, with just too many edge-cases.  And the transparency model is truly terrible to work with -- you can't simply combine pages onto one page with a given transparency per page: you have to encompass them into transparency groups, etc.

I might be able to write something that combines PDF pages, without changing colour or transparency, by simply placing the PDF page contents into x-objects and then drawing those onto the same (new) page, but I don't think I'll get the time to do something like that in at least the next year or 2 -- my day-job is keeping me really busy.

But -- Come to think of it -- I'll probably be able to whip up a LaTeX document for you that does this -- can you send me a set of example PDFs with a brief description of the output you expect so I can give it a shot?  There might even be a Python library that can be used for this -- I'll have a look.

Best of luck.  I believe your use-case is that you'd like to search for something like "R123" in the PDF output that includes the silk layer?  And your CAD tool cannot combine layers for you?

**Comment by jpt13653903** [comment]
In LaTeX, you essentially need to set the paper size to the output you want, with all margins set to zero and "text" width and height equal to the page size.

You then include the PDFs as images -- something along the lines of taking the following 3x PDFs:

- [Red.pdf](https://github.com/jpt13653903/Gerber2PDF/files/12163915/Red.pdf)
- [Green.pdf](https://github.com/jpt13653903/Gerber2PDF/files/12163914/Green.pdf)
- [Blue.pdf](https://github.com/jpt13653903/Gerber2PDF/files/12163912/Blue.pdf)

Which looks like this:

![3xPDFs](https://github.com/jpt13653903/Gerber2PDF/assets/41227383/2db202f8-e5f7-4711-91c3-12d3d5ae626a)

Writing some LaTeX:

```LaTeX
\documentclass{article}

\usepackage{graphicx}

\setlength{\paperwidth} {100mm}
\setlength{\paperheight}{100mm}

\pagestyle{empty}
\setlength{\hoffset}       {-1in}
\setlength{\voffset}       {-1in}
\setlength{\footskip}      {0mm}
\setlength{\headheight}    {0mm}
\setlength{\headsep}       {0mm}
\setlength{\marginparsep}  {0mm}
\setlength{\marginparwidth}{0mm}
\setlength{\textheight}    {\paperheight}
\setlength{\textwidth}     {\paperwidth}
\setlength{\oddsidemargin} {0mm}
\setlength{\topmargin}     {0mm}

\setlength{\parindent}{0mm}
\setlength{\parskip}  {0mm}
\setlength{\lineskip} {0mm}

\begin{document}
  \includegraphics[height=\textheight]{Red}\par%
  \vspace{-\textheight}%
  \includegraphics[height=\textheight]{Green}\par%
  \vspace{-\textheight}%
  \includegraphics[height=\textheight]{Blue}\par%
\end{document}
```

And then compiling using pdfLaTeX (vanilla LaTeX compiles to DVI, and cannot import PDFs, so nobody uses that one anymore).

There are, of course, various packages that can help you with this, such as [geometry](https://ctan.org/pkg/geometry) for setting up the paper size and layout, but I like doing things vanilla wherever possible and or practical.

The result is the PDF below:

[Example.pdf](https://github.com/jpt13653903/Gerber2PDF/files/12163907/Example.pdf)

Which looks like:

![image](https://github.com/jpt13653903/Gerber2PDF/assets/41227383/20ad15fe-194a-4d58-a66f-288c06b4b60c)

**Comment by jpt13653903** [comment]
Another option you can try is running the PDFs through [InkScape](https://inkscape.org/).  The newer versions have really powerful command-line scripting, but, depending on what you want to achieve, I'd stick with LaTeX or Python.

**Comment by jpt13653903** [comment]
I just checked...  LaTeX preserves transparency correctly (as long as the original PDFs have transparency):

![image](https://github.com/jpt13653903/Gerber2PDF/assets/41227383/03c14ca5-26a1-4ef3-aaf3-e81892c10695)

If you'd like to play with the three circles, the original SVG is below.  I used InkScape to create the file and exported the 3 layers to 3 individual PDFs.

![RGB](https://github.com/jpt13653903/Gerber2PDF/assets/41227383/7c3df3b5-fa93-4b83-b951-6b4e0ffb662b)

**Comment by Dzarda7** [comment]
You are awesome, thank you so much. That is it, we were doing it in inkscape, but it took like a day to do everything. I will try to automate it with tools you proposed. Once again thank you so much, you are awesome.
