### ISSUE TITLE
Executable not in download_bug_?

### ISSUE THREAD

**Issue by TeeOneDee** [jpt13653903/Gerber2PDF#9]
**Label**
Bug reports should carry the _bug_ label.

**Alternative Bug List**
Please consult the [SourceForge Discussion](https://sourceforge.net/p/gerber2pdf/discussion) page before reporting a bug here.

**Describe the bug**

From SF, download. Saved to folder. Opened folder, clicked on .exe. DOS opens, with some notes and says press enter to continue. Pressed enter. DOS screen closes. Nothing else happens. The .exe file is the only file downloaded, i.e. no readme, etc.

So, I downloaded it, from GitHub. Unzipped it. Can't find an .exe file, to tell it to run. However, I did get some other file types... Readme, etc.

**To Reproduce**
Steps to reproduce the behaviour.  Attach a minimal example source file, if applicable.
I tried repeated downloads, with the same results
**Expected behavior**
I expected the DOS screen to close and the Start page/screen to open.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1.3]
Windows 8.5, current version, as it updates automatically.
**Additional context**

Please advise.

**Comment by jpt13653903** [comment]
Hi,

The executable is not part of the source, so when you download the source from GitHub, you won't get the exe.  The only place you can get a pre-built version is from SourceForge.

When you run the exe, you should see a console window that prints out usage instructions, as follows:

```
Usage: Gerber2pdf [-silentexit] [-nowarnings] [-output=output_file_name] ...
       [-background=R,G,B[,A]] [-strokes2fills] ...
       file_1 [-combine] file_2 ... [-colour=R,G,B[,A]] [-mirror] ...
       [-nomirror] [-nocombine] ... file_N

Example: Gerber2pdf -output=My_Project
         top_silk.grb bottom_silk.grb
         top_copper.grb inner_copper_1.grb
         inner_copper_2.grb bottom_copper.grb
         bottom_solder_mask.grb top_solder_mask.grb
         board_outline.grb
         -combine -mirror
         -colour=255,0,0     bottom_copper.grb
         -colour=0,128,0,200 bottom_solder_mask.grb
         -colour=0,0,255     board_outline.grb
         -combine -nomirror
         -colour=255,0,0     top_copper.grb
         -colour=0,128,0,200 top_solder_mask.grb
         -colour=0,0,255     board_outline.grb

The -silentexit option disables the pause on exit.
The -nowarnings option disables deprecated feature warnings.

The optional -background colour is either transparent or opaque.  The
threshold is A=128.  Set it just before the target page is created.  Take
care when using this option, because this background colour is used to
draw the copper pour cut-outs.  That same colour will therefore apply
for every subsequent use of that layer, irrespective of the "current"
background colour.  To work around this limitation, use separate Gerber
files for every different background colour.

The -strokes2fills option converts all strokes to fills for the next
file, thereby converting outlines to areas.  This option has to be
applied to the first instance of that file, and applies to all other
instances.  To work around this limitation,
make a copy of the file in question.

Press Enter to continue
```

You can download a minimal example from [SourceForge](https://sourceforge.net/projects/gerber2pdf/files/Example/).  I should probably add that to the read-me...  Gerber2PDF is a command-line tool, so there is no "start screen", as, per definition, there is no GUI.  The tool generates .pdf files, which you can then open / view in your favourite PDF viewer.

The easiest way to use is to use Windows Explorer to open a gerber file using Gerber2PDF.  You use the "open with" feature of Windows Explorer to do this.  The intended usage is by means of a .bat file, however.

**Comment by TeeOneDee** [comment]
Hi, John-Philip,

Thank you for your f-a-s-t reply. Please understand that I tried the SF download first. And, the DOS screen opens, but after pressing enter, the DOS screen closes and nothing else happens... The program does not open, to use it.

I have found a work-around, so I can get by, without it. So, thank you.
____________________________________________________________
How Older Men Are Building Muscle
Celebrity Local
http://thirdpartyoffers.netzero.net/TGL3231/5bac94b22efbf14b23fc5st01vuc

**Comment by jpt13653903** [comment]
I suspect you have a misunderstanding regarding how command-line tools work...

The program does open -- it prints out the usage instructions.  After that it closes, because you have not provided it with any input parameters.  There is nothing more -- no GUI, no user interface, nothing.  After it runs through your input parameters it is done, and then closes...
